apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spea2-scheduler-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spea2-scheduler-clusterrole
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
