apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server
data:
  config: |
    {
      "metrics-bind-address": ":8080",
      "kubelet-preferred-address-types": ["InternalIP", "Hostname"],
      "kubelet-timeout": "10s",
      "update-period": "10s"
    }
