apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: my-app
  annotations:
    scheduler.alpha.kubernetes.io/name: test-scheduler
spec:
  containers:
    - name: nginx
      image: nginx
